export const SONGS_PLAY = 'SONGS_PLAY'
export const PLAYLIST_PLAY = 'PLAYLIST_PLAY'
export const ADD_TO_QUEUE = 'ADD_TO_QUEUE'
export const NEXT_SONG = 'NEXT_SONG'
export const PREV_SONG = 'PREV_SONG'
export const SELECT_SONG_PLAY = 'SELECT_SONG_PLAY'